Fix wrong type annotation
grammyjs/rateLimiter pull request #2
Opened 2022-04-17 08:59 UTC by KnorpelSenf

Fixes #1 hopefully.

2022-04-17 09:01 UTC, roj1512 requested changes

2022-04-17 09:01 UTC, roj1512 commented on src/typesAndDefaults.ts
> +  keyGenerator: (ctx: Context) => ctx.from === undefined ? undefined : && ctx.from.id.toString(),
```suggestion
  keyGenerator: (ctx: Context) => ctx.from === undefined ? undefined : ctx.from.id.toString(),
```

2022-04-17 12:03 UTC, KnorpelSenf commented on src/typesAndDefaults.ts
> +  keyGenerator: (ctx: Context) => ctx.from === undefined ? undefined : && ctx.from.id.toString(),
Haha thanks, coded on mobile ._.

2022-04-17 13:52 UTC, roj1512 approved these changes
Thanks, it works!

2022-04-18 17:47 UTC, KnorpelSenf commented
I'll merge and release a fix tomorrow (unless you're faster @Amir-Zouerami).

2022-04-18 19:32 UTC, Amir-Zouerami commented
> I'll merge and release a fix tomorrow (unless you're faster @Amir-Zouerami).

Fastest hands in the west! Btw, thanks for the pull request. I appreciate it.

2022-04-18 19:32 UTC, merged

2022-04-18 19:57 UTC, roj1512 commented
Haha, there are fast hands in the East, too.