Reply always
grammyjs/ratelimiter pull request #6
Opened 2023-01-23 03:31 UTC by ak4zh

Ability to send a rate-limited warning for every message received during the rate-limited time frame.

2023-01-23 03:32 UTC, KnightNiwrem approved these changes

2023-01-23 07:11 UTC, KnorpelSenf approved these changes
LGTM, just a tiny nitpick about docs style

2023-01-23 07:11 UTC, KnorpelSenf commented on src/typesAndDefaults.ts
> +   * @description send the rate limited response for every message during the limit exceeded timeframe
```suggestion
   * @description Send the rate limited response for every message during the limit exceeded timeframe.
```

2023-01-23 11:55 UTC, roj1512 commented on src/rateLimiter.ts
> +    if (hits === options.limit + 1 || (options.replyAlways && hits > options.limit)) {
```suggestion
    if (hits === options.limit + 1 || (options.alwaysReply && hits > options.limit)) {
```

2023-01-23 11:56 UTC, roj1512 requested changes

2023-01-23 11:56 UTC, roj1512 commented on src/rateLimiter.ts
> +    if (hits === options.limit + 1 || (options.replyAlways && hits > options.limit)) {
```suggestion
    if (hits === options.limit + 1 || (options.alwaysReply && hits > options.limit)) {
```

2023-01-23 11:56 UTC, roj1512 commented on src/typesAndDefaults.ts
> +  replyAlways?: boolean;
```suggestion
  alwaysReply?: boolean;
```

2023-01-23 14:24 UTC, roj1512 requested changes
Please edit the PQ title to be more descriptive.

2023-01-23 17:16 UTC, KnorpelSenf approved these changes
I like the fact that it was renamed to `alwaysReply`, I wish I had suggested this myself. Thanks!

2023-01-31 10:46 UTC, roj1512 commented on src/typesAndDefaults.ts
>     * @description Executed Only once in each timeframe. By default it does nothing so the user is not notified of rate-limiting. The middleware simply ignores excessive requests and the user just has
```suggestion
   * @description Executed only once for each limit excess unless alwaysReply is explicitly set to true. By default, it does nothing, meaning that the user is not notified when they exceed the limit. The middleware simply ignores excessive requests and the user is required to wait.
```

2023-01-31 10:47 UTC, roj1512 commented on src/typesAndDefaults.ts
> +   * @description Send the rate limited response for every message during the limit exceeded timeframe.
```suggestion
   * @description Whether to always call onLimitExceeded or not.
```

2023-01-31 11:15 UTC, roj1512 approved these changes
LGTM. Thank you so much!

2023-02-04 03:42 UTC, ak4zh commented
Can you merge this change and push it to npm?

2023-02-04 05:24 UTC, roj1512 commented
@KnorpelSenf

2023-02-04 12:54 UTC, KnorpelSenf commented
Sure, can do this later today. This plugin currently doesn't have a dedicated maintainer. @ak4zh are you interested in taking over?

2023-02-04 12:55 UTC, KnorpelSenf commented
Then you would become a member of the grammyjs organisation on GitHub and you'll be able to merge and publish yourself :D

2023-02-04 13:20 UTC, ak4zh commented
@KnorpelSenf Sounds interesting. I could try that to publish once I get approved.

2023-02-04 22:14 UTC, KnorpelSenf commented
@ak4zh you now have an invitation to become a member of the grammY org. As soon as you accept, I'll make you the maintainer of this plugin, so you'll get admin rights for this repo.

Please DM me your npm name on Telegram (https://t.me/KnorpelSenf) so I can grant you publish permission for this package.

2023-06-16 23:20 UTC, KnorpelSenf commented
@ak4zh are there any updates here?

2023-06-18 04:38 UTC, merged

2023-06-18 09:13 UTC, KnorpelSenf commented
Are you going to perform a minor release?

2023-06-19 08:44 UTC, ak4zh commented
@KnorpelSenf I have pushed the changes as a minor release, thanks for your guidance.